# Generated by Django 4.2.6 on 2023-10-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='created_at',
        ),
    ]
